### ISSUE TITLE
[Feb 17th.] Talking Points - CH5 & CH6

### ISSUE THREAD

**Issue by JonathanLorimer** [barrymoo/ctfp-book-club#19]
This should be a forum for points that we want to discuss in our meeting on `Feb 17`, the material we will be covering is:
- `Chapter 5 - Products and Coproducts`
- `Chapter 6 - Simple Algebraic Data Types`

**Comment by barrymoo** [comment]
Chapter 5: Products and Coproducts
---

- Universal Construction
  - _pattern_: Consider a shape constructed from objects and morphisms, look for all occurrences in a category
  - _recall_: A pattern which yields a lot of examples
  - _precision_: Reducing your recall by refining your pattern
- Initial Objects
  - In Haskell, `absurd :: Void -> a`
- Terminal Objects
  - In Haskell, `unit :: a -> ()`
- Duality
  - For any category, there is a dual category with all of the morphisms flipped
  - The dual category is prefaced with `co-`
  - The initial object in a category becomes the final object in the co-category (and vice-versa)
- Isomorphisms, define functions `a -> b` and `b -> a`
- Cartesian Products and `factorizer`'s i.e. `(&&&)`
  - Projection functions, i.e. `fst :: (a, b) -> a` and `snd`
  - Can consider patterns such as `r :: c -> a` and `s :: c -> b` to produce large recall
  - _rank_
  - Factorization 
- Coproducts e.g. `Either`
  - Opposite of projection is injection
- Asymmetry

**Comment by barrymoo** [comment]
Chapter 6: Simple Algebraic Data Types
---

- Product leads to Product Types e.g. `(,)
  - _empty_ is `()`, similar to 1 for multiplication
- Coproducts lead to Sum Types, e.g. `Either`
  - _empty_ is `Void`, similar to 0 for addition
- The Algebra of Types
- The Curry-Howard Isomorphism

**Comment by barrymoo** [comment]
I skipped the videos because they are a bit too long. I might choose to watch some after our discussion.

**Comment by barrymoo** [comment]
I think [this](https://alexknvl.com/posts/any-is-final-object.html) is really useful. I think it highlights our common issue when trying to avoid observability.

**Comment by JonathanLorimer** [comment]
This is awesome Barry. I am just finishing up CH6 right now. I have my notes in a subdirectory under my name. I will submit a pull request tonight or tomorrow with them.

**Comment by barrymoo** [comment]
Closing this as we are done with the week.
